# Generated by Django 4.2.17 on 2025-01-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_url',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
